{"name":"Log","hostname":"azzaro","pid":4151,"level":50,"err":{"id":"7c888b20-2e1e-11e8-99dc-5f90c60c6781","domain":"http://localhost:2368","code":"ECONNREFUSED","name":"InternalServerError","statusCode":500,"level":"normal","message":"The server has encountered an error.","stack":"InternalServerError: The server has encountered an error.\n    at new GhostError (/home/okozyn/Projects/blog/core/server/lib/common/errors.js:9:26)\n    at /home/okozyn/Projects/blog/index.js:37:15\n    at tryCatcher (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:763:18)\n    at tryOnImmediate (timers.js:734:5)\n    at processImmediate (timers.js:716:5)\n\nError: connect ECONNREFUSED 127.0.0.1:3306\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)\n    --------------------\n    at Protocol._enqueue (/home/okozyn/Projects/blog/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/home/okozyn/Projects/blog/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/home/okozyn/Projects/blog/node_modules/mysql/lib/Connection.js:130:18)\n    at /home/okozyn/Projects/blog/node_modules/knex/lib/dialects/mysql/index.js:109:18\n    at Promise._execute (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/debuggability.js:303:9)\n    at Promise._resolveFromExecutor (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:79:10)\n    at Client_MySQL.acquireRawConnection (/home/okozyn/Projects/blog/node_modules/knex/lib/dialects/mysql/index.js:104:12)\n    at create (/home/okozyn/Projects/blog/node_modules/knex/lib/client.js:269:23)\n    at tryPromise (/home/okozyn/Projects/blog/node_modules/tarn/lib/Pool.js:366:22)\n    at tryPromise (/home/okozyn/Projects/blog/node_modules/tarn/lib/utils.js:57:20)\n    at Promise (/home/okozyn/Projects/blog/node_modules/tarn/lib/Pool.js:366:5)\n    at Promise._execute (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/debuggability.js:303:9)\n    at Promise._resolveFromExecutor (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:79:10)\n    at callbackOrPromise (/home/okozyn/Projects/blog/node_modules/tarn/lib/Pool.js:357:10)"},"msg":"The server has encountered an error.","time":"2018-03-22T22:15:10.812Z","v":0}
{"name":"Log","hostname":"azzaro","pid":4151,"level":50,"err":{"id":"7c888b20-2e1e-11e8-99dc-5f90c60c6781","domain":"http://localhost:2368","code":"ECONNREFUSED","name":"InternalServerError","statusCode":500,"level":"normal","message":"The server has encountered an error.","stack":"InternalServerError: The server has encountered an error.\n    at new GhostError (/home/okozyn/Projects/blog/core/server/lib/common/errors.js:9:26)\n    at /home/okozyn/Projects/blog/index.js:37:15\n    at tryCatcher (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:763:18)\n    at tryOnImmediate (timers.js:734:5)\n    at processImmediate (timers.js:716:5)\n\nError: connect ECONNREFUSED 127.0.0.1:3306\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)\n    --------------------\n    at Protocol._enqueue (/home/okozyn/Projects/blog/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/home/okozyn/Projects/blog/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/home/okozyn/Projects/blog/node_modules/mysql/lib/Connection.js:130:18)\n    at /home/okozyn/Projects/blog/node_modules/knex/lib/dialects/mysql/index.js:109:18\n    at Promise._execute (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/debuggability.js:303:9)\n    at Promise._resolveFromExecutor (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:79:10)\n    at Client_MySQL.acquireRawConnection (/home/okozyn/Projects/blog/node_modules/knex/lib/dialects/mysql/index.js:104:12)\n    at create (/home/okozyn/Projects/blog/node_modules/knex/lib/client.js:269:23)\n    at tryPromise (/home/okozyn/Projects/blog/node_modules/tarn/lib/Pool.js:366:22)\n    at tryPromise (/home/okozyn/Projects/blog/node_modules/tarn/lib/utils.js:57:20)\n    at Promise (/home/okozyn/Projects/blog/node_modules/tarn/lib/Pool.js:366:5)\n    at Promise._execute (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/debuggability.js:303:9)\n    at Promise._resolveFromExecutor (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:79:10)\n    at callbackOrPromise (/home/okozyn/Projects/blog/node_modules/tarn/lib/Pool.js:357:10)"},"msg":"The server has encountered an error.","time":"2018-03-22T22:15:10.812Z","v":0}
{"name":"Log","hostname":"azzaro","pid":4161,"level":50,"err":{"id":"822aa6d0-2e1e-11e8-b514-cb5afc087c09","domain":"http://localhost:2368","code":"ECONNREFUSED","name":"InternalServerError","statusCode":500,"level":"normal","message":"The server has encountered an error.","stack":"InternalServerError: The server has encountered an error.\n    at new GhostError (/home/okozyn/Projects/blog/core/server/lib/common/errors.js:9:26)\n    at /home/okozyn/Projects/blog/index.js:37:15\n    at tryCatcher (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:763:18)\n    at tryOnImmediate (timers.js:734:5)\n    at processImmediate (timers.js:716:5)\n\nError: connect ECONNREFUSED 127.0.0.1:3306\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)\n    --------------------\n    at Protocol._enqueue (/home/okozyn/Projects/blog/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/home/okozyn/Projects/blog/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/home/okozyn/Projects/blog/node_modules/mysql/lib/Connection.js:130:18)\n    at /home/okozyn/Projects/blog/node_modules/knex/lib/dialects/mysql/index.js:109:18\n    at Promise._execute (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/debuggability.js:303:9)\n    at Promise._resolveFromExecutor (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:79:10)\n    at Client_MySQL.acquireRawConnection (/home/okozyn/Projects/blog/node_modules/knex/lib/dialects/mysql/index.js:104:12)\n    at create (/home/okozyn/Projects/blog/node_modules/knex/lib/client.js:269:23)\n    at tryPromise (/home/okozyn/Projects/blog/node_modules/tarn/lib/Pool.js:366:22)\n    at tryPromise (/home/okozyn/Projects/blog/node_modules/tarn/lib/utils.js:57:20)\n    at Promise (/home/okozyn/Projects/blog/node_modules/tarn/lib/Pool.js:366:5)\n    at Promise._execute (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/debuggability.js:303:9)\n    at Promise._resolveFromExecutor (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:79:10)\n    at callbackOrPromise (/home/okozyn/Projects/blog/node_modules/tarn/lib/Pool.js:357:10)"},"msg":"The server has encountered an error.","time":"2018-03-22T22:15:20.262Z","v":0}
{"name":"Log","hostname":"azzaro","pid":4161,"level":50,"err":{"id":"822aa6d0-2e1e-11e8-b514-cb5afc087c09","domain":"http://localhost:2368","code":"ECONNREFUSED","name":"InternalServerError","statusCode":500,"level":"normal","message":"The server has encountered an error.","stack":"InternalServerError: The server has encountered an error.\n    at new GhostError (/home/okozyn/Projects/blog/core/server/lib/common/errors.js:9:26)\n    at /home/okozyn/Projects/blog/index.js:37:15\n    at tryCatcher (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:763:18)\n    at tryOnImmediate (timers.js:734:5)\n    at processImmediate (timers.js:716:5)\n\nError: connect ECONNREFUSED 127.0.0.1:3306\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)\n    --------------------\n    at Protocol._enqueue (/home/okozyn/Projects/blog/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/home/okozyn/Projects/blog/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/home/okozyn/Projects/blog/node_modules/mysql/lib/Connection.js:130:18)\n    at /home/okozyn/Projects/blog/node_modules/knex/lib/dialects/mysql/index.js:109:18\n    at Promise._execute (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/debuggability.js:303:9)\n    at Promise._resolveFromExecutor (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:79:10)\n    at Client_MySQL.acquireRawConnection (/home/okozyn/Projects/blog/node_modules/knex/lib/dialects/mysql/index.js:104:12)\n    at create (/home/okozyn/Projects/blog/node_modules/knex/lib/client.js:269:23)\n    at tryPromise (/home/okozyn/Projects/blog/node_modules/tarn/lib/Pool.js:366:22)\n    at tryPromise (/home/okozyn/Projects/blog/node_modules/tarn/lib/utils.js:57:20)\n    at Promise (/home/okozyn/Projects/blog/node_modules/tarn/lib/Pool.js:366:5)\n    at Promise._execute (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/debuggability.js:303:9)\n    at Promise._resolveFromExecutor (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/okozyn/Projects/blog/node_modules/bluebird/js/release/promise.js:79:10)\n    at callbackOrPromise (/home/okozyn/Projects/blog/node_modules/tarn/lib/Pool.js:357:10)"},"msg":"The server has encountered an error.","time":"2018-03-22T22:15:20.262Z","v":0}
